{% set version = "1.0.0" %}

package:
  name: pythonDev
  version: {{ version }}

source:
  git_url: https://github.com/joey-lou/python-dev
  git_rev: {{ version }}
  git_depth: -1

requirements:
  develop:
    - autoflake
    - black
    - invoke==1.4.1
    - isort==5.6.*
    - click==7.1.*
    - jupyterlab
    - pylint
    - flask
  run:
    - twilio
    - sendgrid
    - Flask-WTF
    - email_validator
    - flask-sqlalchemy
    - pydantic==1.7.3
    - requests==2.25.0
    - beautifulsoup4==4.9.3
    - spotipy
    - selenium
    - fake_useragent