{% set version = "1.0.0" %}

package:
  name: pythonDev
  version: {{ version }}

source:
  git_url: https://github.com/joey-lou/python-dev
  git_rev: {{ version }}
  git_depth: -1

requirements:
  build:
    python=3.7.9
  develop:
    autoflake
    black
    invoke=1.4.1
    isort=5.6.*
    click=7.1.*
  run:
    pydantic=1.7.3
    requests=2.25.0

